### ISSUE TITLE
Repository obsolete?

### ISSUE THREAD

**Issue by ejgallego** [frasertweedale/docker-coq#1]
Dear @frasertweedale , it seems this repository is obsolete now, in favor of https://github.com/coq-community/docker-coq

Would it be a good option to remove it so users googling may potentially have less source for confusion?

**Comment by frasertweedale** [comment]
Obsolete?  Yes.  Remove?  No.  But I'll soon (next week or so) update the README to point to the other thing (which I did not know about).

Thanks,
Fraser

**Comment by ejgallego** [comment]
Thanks!

**Comment by frasertweedale** [comment]
Added README with link.  Closing this now.
